language: node_js
node_js:
  - '9'
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: yk7sy72S4S8gDzN48GVeyy3KTEvY9wz+tTB5N20G9J5iLesefpoDGrSXMFb6Yy1sHbyy75U30OSjac75Wngvb5k93Crh8aiMjr4itmZBnkIM6PHabQm0mnWpSzgO2PIlK6xWO++eqWjpLAv6SdxV+WiCwexRds+0W96+kX6VoTvQFTKgtGPdj2R2bUE+RN86zQkmMmpkFLlOLmDaOXXJKbjZezIalFMcL5lvuLyeRt3wl5McXqg/hgsLUxkaCJg0PHqoYFocPwimwSnxbdZtNtHTPGMtW0ayLqq9UaHxa4+2h1QEeFwgsLdYppv+Rh0xw6YcSPuB9Qwm9+h7212SdPe+fXnw2+q0vUmaL2ZKIKboNdQeB1xS9m3PwSnRf1fJPiv82f3GOiGOvnakqNJ1lIJoNFDOgwHL/14+3XW1HaJDPuCYwdGzQ6W8NDpn3kddGL3KnvGayykxKUp/NvDAzC6onIQSo97nq+BPtPrTgL80lk3gqIxtmMlPzkR0N36h/FIg+rq9AYfCv5pQdSs7CqFUY8bVxdEXzmjze5iw1VtdgPZnJNv3d4+DW2+d5V8cNKs2IcvNIu1LkWpe2Yuqy76rVSDA940SJJdhfNFxcmm8GRXRFcNWu0LE8sGuzinZhPaJXmM1O6iZo6YDafb9XuiGSjXqdpKbgDipgtOhDEU=
  app: text-compare-angular