language: node_js
node_js:
  - "9"

branches:
  only:
  - master

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: text-compare-angular