language: node_js
node_js:
  - "8"

before_install:
  - npm install -g @angular/cli

  install: npm install

branches:
  only:
  - master

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: text-compare-angular