apiVersion: v1
kind: Service
metadata:
  name: compare-helm
  namespace: {{ .Values.namespace }}
  labels:
    app: compare-helm
spec:
  selector:
    app: compare-helm
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    type: NodePort